set_property SRC_FILE_INFO {cfile:C:/Users/Kin/Desktop/FPGA/8_fifo_ip/8_fifo_ip/8_fifo_ip.srcs/constrs_1/new/fifo_ip.xdc rfile:../../../8_fifo_ip.srcs/constrs_1/new/fifo_ip.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R4 [get_ports sys_clk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports sys_rst_n]
